#! /bin/bash

read -p "Enter your password: " password

if [ ${#password} -ge 8 ]; then
    echo "Password is valid!"
else
    echo "Password is too short. Please enter a password with at least 8 characters."
fi